### ISSUE TITLE
peer feedback - tutorial notebook plotting issues: fit_quad() on real data

### ISSUE THREAD

**Issue by mcooper12** [phys201/icetemp#12] opened 2021-04-26 17:18 UTC
When I close the repository and run the tutorial notebook from jupyterlab, I get these plots in cell [6]:

![image](https://user-images.githubusercontent.com/55110657/116123985-af830480-a691-11eb-91bb-61332131e540.png)

These definitely aren't the intended plot. The best fit values that are printed above these plots look fine, though.

**Comment by diyaselis** [comment] 2021-04-26 20:41
The genesis of the problem is that initially data from the detector is given as heights, meaning that because the detector is submerged in ice the heights are negative. Our convention is to define these points as depth, which we take as positive. 

We were doing these definitions manually, and we are transitioning to make it an automatic process inside our `data_io.py`. You could've caught it while we are updating the notebook. Thanks for racing the concern.

**Comment by diyaselis** [comment] 2021-04-26 20:50
Should be fixed by now, please try again!

**Closed as completed by diyaselis** 2021-04-26 20:50 UTC
